name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Find Yarn Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - name: Run yarn
        run: yarn
      - name: Find linting & testing Cache
        uses: actions/cache@v1
        with:
          path: cache
          key: lintingcache-${{ hashFiles('yarn.lock')}}
          restore-keys: lintingcache-
      - name: Check ESLint
        run: yarn lint:cache
      - name: Check code style
        run: yarn format:prettier
      - name: Run unit test
        run: yarn test
      - name: Build Typescript
        run: yarn build
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish
